name: Build Release

on: [ workflow_dispatch ]

jobs:
  release:
    name: Build Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Prepare Maven Release
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          ./mvnw -B release:prepare -DtagNameFormat='@{project.version}' -Darguments='-Dmaven.javadoc.skip -Dmaven.source.skip'
      - name: Determin Release Tag
        run: |
          echo "GIT_TAG=$(awk -F= '/^scm.tag=/ {print $2}' release.properties)" >> $GITHUB_ENV
      - name: Perform Maven Release
        run: |
          ./mvnw -B release:perform -Dusername=${{ github.actor }} -Dpassword=${{ secrets.GITHUB_TOKEN }} -Dgoals=package -Darguments='-Dmaven.javadoc.skip'
      - name: Sign Artifacts
        run: |
          echo -e "${{ secrets.GPG_SECRET_KEY }}" | gpg --batch --import
          for file in target/checkout/plugin/target/apm-wildfly-remote-ejb-plugin-*.jar; do
            gpg --batch --pinentry-mode loopback --passphrase "${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}" --output $file.sig --sign --detach-sig $file
          done
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          tag: ${{ env.GIT_TAG }}
          artifacts: target/checkout/plugin/target/apm-wildfly-remote-ejb-plugin-*.jar,target/checkout/plugin/target/apm-wildfly-remote-ejb-plugin-*.jar.sig
